name: CI Preprocessing
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Jalankan preprocessing
        run: |
          python automate_Duma-Mora-Arta-Sitorus.py